project:
  type: website
  resources:
    - data
    - img
    - outputs/**
  output-dir: docs

website:
  title: "Overdosed"
  favicon: "img/gu-logo.png"
  navbar:
    search: true
    left:
      - href: about.qmd
        text: About
      - href: index.html
        text: Dashboard
      - href: findings.html
        text: Findings
      - href: references.html
        text: References  
    right:
      - icon: github
        href: "https://github.com/gu-dsan5200/dsan5200-spring2025-project-group-04.git"

  
format:
  html:
      theme: 
        - morph
        - styles.scss
      toc: true
      toc-location: right
      toc-depth: 4

#editor: visual