project:
  type: website
  resources:
    - data
    - images
  output-dir: docs

website:
  title: "DSAN 5200"
  favicon: "images/gu-logo.png"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Homepage
    
    right:
      - icon: github
        href: "https://github.com/ikd2-crg123-yg429-sr1672/ikd2-crg123-yg429-sr1672.io.git"

  
format:
  html:
    toc: true
    toc-location: left
    toc-depth: 4

editor: visual